### ISSUE TITLE
Display magnitute and intensity per station when earthquake is detected.

### ISSUE THREAD

**Issue by JABirchall** [xspanger3770/GlobalQuake#209] opened 2024-01-23 03:37 UTC
This is a feature in JQuake which think is quiet useful, is to display the magnitude and intensity of an earthquake felt by each station. 

JQuake style
![](https://i.imgur.com/dkz6ySP.png)

Shindo Style
![](https://i.imgur.com/n8nYgHd.png)

**Comment by xspanger3770** [comment] 2024-01-26 20:07
Unfortunately this feature isn't really possible to implement accurately, since most global stations are broadband seismometers that are unable to record high shaking intensity unlike accelerometers in Japan that are built to measure very strong shaking.

**Comment by JABirchall** [comment] 2024-01-26 21:09
> Unfortunately this feature isn't really possible to implement accurately, since most global stations are broadband seismometers that are unable to record high shaking intensity unlike accelerometers in Japan that are built to measure very strong shaking.

I wonder if there is a way to know if a statation is sufficiant enough to display magnitute for that station. As on jquake some stations also dont display magnitude only showing colour as globalquake does now.

**Comment by xspanger3770** [comment] 2024-07-21 20:19
Duplicate of #101

**Closed by xspanger3770** 2024-07-21 20:19 UTC
Labels: duplicate, feature
